# Config Server to Connect with Service Discovery
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}


# This is like ternary operator
# when Env available it will use constant if not it will use URL


